### ISSUE TITLE
Show rendering of selected value?

### ISSUE THREAD

**Issue by smertens-npr** [TatuLund/ColorPicker#5]
1. The color picker only shows the string captions for colors when the combo-box is dropped down.  Can it be made to show the rendered caption of the selected color?  Right now the color box has the right color, but the text field is left blank.

2. Also, would it be possible to optionally allow custom rendering code to render the caption string?  Or perhaps allow it to be a component?  We have a use case where we want more formatting than just a simple text string insertion.

Thank you much.

**Comment by eberleant** [comment]
Adding onto the first question: If the default behavior of clearing the combobox after input can't be changed, would it be possible to add a method like `setClearAfterInput(boolean)` to configure it?

**Comment by TatuLund** [comment]
@eberleant 

> Adding onto the first question: If the default behavior of clearing the combobox after input can't be changed

The behavior is intentional. There is even integration test for that

https://github.com/TatuLund/ColorPicker/blob/master/src/test/java/org/vaadin/addons/tatu/AbstractColorPickerIT.java#L187

I chose this approach as you can type the color into field using alternative formats, but all of them are eventually translated to hex-value, which is sent to server.

E.g. rgb(255,0,0) and #ff0000 convert to same actual value. Thus I find not logical if the text stays rgb(255,0,0). Also clearing the value is slightly more usable when modifying value by typing.

> to add a method like setClearAfterInput(boolean) to configure it?

Technically that is doable. I am just wondering that in that case the text should be autoselected, so that you do not need to delete it if you type in new value.

**Comment by TatuLund** [comment]
Check version 1.4.0, it has the both features

1. Use setNoClear(true), it has been implemented according to previous comment
2. You can use CaptionMode.HTML for more rich captions

![image](https://github.com/TatuLund/ColorPicker/assets/14309836/c6fe6d32-f8ea-4957-a548-e8abd7a97ce7)

**Comment by smertens-npr** [comment]
Thank you!  Just need 1.4.0 to show up in the maven repositories and then we'll be able to use it.
